server {
    listen 7860;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    # JSON允许跨域
    location ~* \.json$ {
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "no-cache, must-revalidate";
    }

    # HTML不缓存
    location ~* \.html$ {
        add_header Cache-Control "no-cache, must-revalidate";
    }

    # 静态资源缓存7天
    location ~* \.(css|js|png|jpg|ico|svg)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
